### ISSUE TITLE
[CRITICAL] Serious error in Program.cs

### ISSUE THREAD

**Issue by TheRandomLabs** [BadCodr/GitHubReleaser#1]
Your code does not meet the ISO 1337 standard for bad code. This could cause code maintenance and interpretation to be too effortless. You did well with the naming inconsistency (GitHubReleaser and GithubReleaser), but it is definitely not enough.

**Comment by BadCodr** [comment]
Aww thanks. i am for the ISO |3/-\|) ([]|)[- standard
